# fly.toml file generated for megalearn-frontend on 2023-02-01T15:02:18+09:00

app = "megalearn-frontend"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  CLOUDINARY_NAME="dp8pijjeo"
  CLOUDINARY_KEY="392114978863173"
  CLOUDINARY_SECRET="TcmEsfUNvwcgnIROaaa5rKk52Xw"
  REACT_APP_KAKAO_JS_KEY="f68e74cb36b27a454feabfe98615162d"
  REACT_APP_KAKAO_REDIRECT_URL="https://megalearn-frontend.fly.dev"
  REACT_APP_API_BASE_URL="https://megalearn-backend.herokuapp.com"
  REACT_APP_FRONT_BASE_URL="https://megalearn-frontend.fly.dev"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
